### ISSUE TITLE
Trouble install directly from pip

### ISSUE THREAD

**Issue by burkesquires** [bjpop/rubra#27]
Hello,
I tried installing directly from pip and got the following errors:

pip install git+git://github.com/bjpop/rubra
Collecting git+git://github.com/bjpop/rubra
  Cloning git://github.com/bjpop/rubra to /private/var/folders/d7/8vn6rd1d6f37gtgy_13h3b95mx3fmv/T/pip-fvxy0kg6-build
Collecting ruffus==2.2 (from Rubra==0.1.5)
  Downloading ruffus-2.2.zip (5.9MB)
    100% |████████████████████████████████| 5.9MB 115kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/d7/8vn6rd1d6f37gtgy_13h3b95mx3fmv/T/pip-build-wo2ofvka/ruffus/setup.py", line 2, in <module>
        import ez_setup
      File "/private/var/folders/d7/8vn6rd1d6f37gtgy_13h3b95mx3fmv/T/pip-build-wo2ofvka/ruffus/ez_setup.py", line 98
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/d7/8vn6rd1d6f37gtgy_13h3b95mx3fmv/T/pip-build-wo2ofvka/ruffus/

**Comment by bjpop** [comment]
Hi @burkesquires. Thanks for the bug report. Looks like a problem with the version of Python being used.

We don't use rubra anymore, since most of its useful parts became absorbed into Ruffus. Perhaps you might have better luck working with Ruffus directly, or having a look at some of the code we've written around it:

https://github.com/bjpop/pipeline_base
And a trivial example:
https://github.com/bjpop/test_ruffus_pipeline
